services:
  redis:
    image: redis:7
    # ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - minio-data:/data

  langgraph:
    build: .
    environment:
      LG_TOKEN: "LG_SECRET"
      MAIN_TOKEN: "MAIN_SECRET"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin12345"
      MINIO_BUCKET: "roi"
      REDIS_URL: "redis://redis:6379/0"
      CMD_STREAM: "yolo_cmd"
      EVT_STREAM: "yolo_events"
      STATUS_KEY: "yolo_status"
      SHARED_UPLOADS: "/shared/uploads" # only if you switch to host-dir sharing
    depends_on: [minio, redis]
    ports:
      - "9100:9000"
    # If you want host-dir file sharing instead of MinIO, uncomment:
    # volumes:
    #   - ./shared:/shared:rw

volumes:
  minio-data:
